//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probachetyre
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч рег вх гост.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРегВхГост CustomAttributes)

    // *** End programmer edit section *** (ТЧРегВхГост CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч рег вх гост")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРегВхГостE", new string[] {
            "Гость as \'Гость\'",
            "Гость.Фамилия as \'Фамилия\'",
            "Карты as \'Карты\'",
            "Карты.КодКарты as \'Код карты\'"})]
    [MasterViewDefineAttribute("ТЧРегВхГостE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ТЧРегВхГостE", "Карты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Код карты")]
    public class ТЧРегВхГост : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probachetyre.Гость fГость;
        
        private IIS.Probachetyre.Карты fКарты;
        
        private IIS.Probachetyre.ФормаРегВхода fФормаРегВхода;
        
        // *** Start programmer edit section *** (ТЧРегВхГост CustomMembers)

        // *** End programmer edit section *** (ТЧРегВхГост CustomMembers)

        
        /// <summary>
        /// Т ч рег вх гост.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхГост.Гость CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхГост.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Probachetyre.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхГост.Гость Get start)

                // *** End programmer edit section *** (ТЧРегВхГост.Гость Get start)
                IIS.Probachetyre.Гость result = this.fГость;
                // *** Start programmer edit section *** (ТЧРегВхГост.Гость Get end)

                // *** End programmer edit section *** (ТЧРегВхГост.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхГост.Гость Set start)

                // *** End programmer edit section *** (ТЧРегВхГост.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ТЧРегВхГост.Гость Set end)

                // *** End programmer edit section *** (ТЧРегВхГост.Гость Set end)
            }
        }
        
        /// <summary>
        /// Т ч рег вх гост.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхГост.Карты CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхГост.Карты CustomAttributes)
        [PropertyStorage(new string[] {
                "Карты"})]
        [NotNull()]
        public virtual IIS.Probachetyre.Карты Карты
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхГост.Карты Get start)

                // *** End programmer edit section *** (ТЧРегВхГост.Карты Get start)
                IIS.Probachetyre.Карты result = this.fКарты;
                // *** Start programmer edit section *** (ТЧРегВхГост.Карты Get end)

                // *** End programmer edit section *** (ТЧРегВхГост.Карты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхГост.Карты Set start)

                // *** End programmer edit section *** (ТЧРегВхГост.Карты Set start)
                this.fКарты = value;
                // *** Start programmer edit section *** (ТЧРегВхГост.Карты Set end)

                // *** End programmer edit section *** (ТЧРегВхГост.Карты Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probachetyre.ФормаРегВхода.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхГост.ФормаРегВхода CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхГост.ФормаРегВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ФормаРегВхода"})]
        public virtual IIS.Probachetyre.ФормаРегВхода ФормаРегВхода
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Get start)

                // *** End programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Get start)
                IIS.Probachetyre.ФормаРегВхода result = this.fФормаРегВхода;
                // *** Start programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Get end)

                // *** End programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Set start)

                // *** End programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Set start)
                this.fФормаРегВхода = value;
                // *** Start programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Set end)

                // *** End programmer edit section *** (ТЧРегВхГост.ФормаРегВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРегВхГостE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРегВхГостE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРегВхГостE", typeof(IIS.Probachetyre.ТЧРегВхГост));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧРегВхГост.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхГост CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхГост CustomAttributes)
    public class DetailArrayOfТЧРегВхГост : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probachetyre.DetailArrayOfТЧРегВхГост members)

        // *** End programmer edit section *** (IIS.Probachetyre.DetailArrayOfТЧРегВхГост members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧРегВхГост by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧРегВхГост.
        /// </summary>
        public DetailArrayOfТЧРегВхГост(IIS.Probachetyre.ФормаРегВхода fФормаРегВхода) : 
                base(typeof(ТЧРегВхГост), ((ICSSoft.STORMNET.DataObject)(fФормаРегВхода)))
        {
        }
        
        public IIS.Probachetyre.ТЧРегВхГост this[int index]
        {
            get
            {
                return ((IIS.Probachetyre.ТЧРегВхГост)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probachetyre.ТЧРегВхГост dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
